version: '3.1'
services:
  springboot:
    image: jabdockerpro/spring:1 .
    restart: always 
    ports:
    - 8080:8080
    container_name: springappcontainer
    networks:
    - springappcustombridge
  mongo:
    image: mongo
    volumes:
    - mongodb:/data/db
    restart: always
    networks:
    - springappcustombridge
volumes:
  mongodb:
    driver: local
networks:
  springappcustombridge:
  
