version: '3.1'

services:
  springboot:
    image: jabdockerpro/spring-boot-mongo:1
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    ports:
    - 8080:8080
    container_name: springappcontainer
    networks:
    - springappcustombridge
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
    - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
 volumes:
   mongodb:
     driver: local
 networks:
   springappcustombridge
  
